server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8090


spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/tracking
    username: postgres
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  logging:
    level: org.hibernate.SQL=error



